set -g default-terminal "xterm-256color"

# remap prefix to ctrl - a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# remap v-split and h-split to sane keys
bind = split-window -h
bind - split-window -v
unbind '"'
unbind %

# ?? from old config
set-option -g default-terminal "screen-256color"
set-option -g focus-events on
set-option -sg escape-time 10
set-option -sa terminal-overrides ',screen:RGB'

# vim motions to resize panes
bind -r C-h resize-pane -L
bind -r C-j resize-pane -D
bind -r C-k resize-pane -U
bind -r C-l resize-pane -R

# vim motion to switch left/right
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

unbind Up
unbind Down
unbind Left
unbind Right

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right
