#!/usr/bin/env sh

yabai -m space 1 --label "terminal"
yabai -m space 2 --label "safari"
yabai -m space 3 --label "temp"
yabai -m space 4 --label "browser"
yabai -m space 5 --label "obsidian"
yabai -m space 6 --label "finder"
yabai -m space 7 --label "bitwarden"
yabai -m space 8 --label "settings"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config window_placement             second_child
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config focus_follows_mouse          off
yabai -m config mouse_follows_focus          off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config window_topmost               off

# general space settings
yabai -m config layout                       bsp

yabai -m rule --add app="iTerm"                 space=1
yabai -m rule --add app="Safari"                space=2
yabai -m rule --add app="Brave Browser"         space=4
yabai -m rule --add app="Obsidian"              space=5
yabai -m rule --add app="Finder"                space=6
yabai -m rule --add app="Bitwarden"             space=7
yabai -m rule --add app="System\ Settings"      space=8

# spacebar padding on top screen
yabai -m config external_bar all:0:29

echo "yabai configuration loaded.."
