vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "H", "0")
vim.keymap.set("n", "L", "$")
vim.keymap.set("n", "<leader>;", "<C-w>l")
vim.keymap.set("n", "<leader>a", "<C-w>h")
vim.keymap.set("n", "<leader>t", "<cmd>vert terminal<CR>")
vim.keymap.set("n", "zz", "<cmd>w<CR>")
vim.keymap.set("n", "ZZ", "<cmd>wq<CR>")
vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("n", "<leader>bn", "<cmd>bnext<CR>")
vim.keymap.set("n", "<leader>bp", "<cmd>bprevious<CR>")
vim.keymap.set("n", "<leader>bd", "<cmd>bdelete<CR>")
vim.keymap.set("n", "<leader>ev", "<cmd>vsplit /home/boater/.config/nvim<CR>")
vim.keymap.set("n", "<leader>sv", "<cmd>vsplit /home/boater/.config/nvim/init.lua<CR>")
vim.keymap.set("n", "<leader><leader>", function()
    vim.cmd("so")
end)
vim.keymap.set("n", "<leader>o", "o<Esc>k")
vim.keymap.set("n", "<leader>O", "O<Esc>j")
